2024-12-02 12:42:23,485 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/honda/civic
2024-12-02 12:43:30,952 - web_analyzer - WARNING - Timeout waiting for selector .original-catalog-page
2024-12-02 12:43:30,996 - web_analyzer - INFO - Saved HTML to web_analyzer\output\20241202_124330_civic.html
2024-12-02 12:43:31,129 - web_analyzer - INFO - Saved screenshot to web_analyzer\output\20241202_124330_civic.png
2024-12-02 12:45:33,878 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/honda/civic
2024-12-02 12:46:40,240 - web_analyzer - WARNING - Timeout waiting for selector .original-catalog-page
2024-12-02 12:46:40,290 - web_analyzer - INFO - Saved HTML to web_analyzer\output\20241202_124640_civic.html
2024-12-02 12:46:40,715 - web_analyzer - INFO - Saved full page screenshot to web_analyzer\output\20241202_124640_civic.png
2024-12-02 12:54:46,859 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 12:54:48,526 - web_analyzer - ERROR - Error saving response data: Response.text: Response body is unavailable for redirect responses
2024-12-02 12:54:50,487 - web_analyzer - ERROR - Error saving response data: Response.text: Response body is unavailable for redirect responses
2024-12-02 12:54:51,365 - web_analyzer - ERROR - Error saving response data: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 12:54:56,261 - web_analyzer - ERROR - Error saving response data: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 12:55:53,313 - web_analyzer - WARNING - Timeout waiting for selector .original-catalog-page
2024-12-02 12:55:55,135 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 12:55:56,598 - web_analyzer - WARNING - Could not get response body: Response.text: Response body is unavailable for redirect responses
2024-12-02 12:55:58,152 - web_analyzer - WARNING - Could not get response body: Response.text: Response body is unavailable for redirect responses
2024-12-02 12:55:58,761 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 12:55:58,792 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 12:55:58,890 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 12:55:59,151 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 12:56:00,752 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
2024-12-02 12:56:02,110 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0xca in position 12: invalid continuation byte
2024-12-02 12:56:02,322 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
2024-12-02 12:56:03,655 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 12:56:59,994 - web_analyzer - WARNING - Timeout waiting for selector .original-catalog-page
2024-12-02 12:57:00,161 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный: [Errno 22] Invalid argument: 'web_analyzer\\output\\20241202_125555_quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный.html'
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 234, in analyze_page
    html_path.write_text(html, encoding='utf-8')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
OSError: [Errno 22] Invalid argument: 'web_analyzer\\output\\20241202_125555_quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный.html'
2024-12-02 12:59:12,827 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 12:59:15,574 - web_analyzer - WARNING - Could not get response body: Response.text: Response body is unavailable for redirect responses
2024-12-02 12:59:17,557 - web_analyzer - WARNING - Could not get response body: Response.text: Response body is unavailable for redirect responses
2024-12-02 12:59:18,149 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 12:59:18,175 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 12:59:18,275 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 12:59:18,575 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 12:59:20,378 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x9b in position 1: invalid start byte
2024-12-02 12:59:21,666 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0xcf in position 5: invalid continuation byte
2024-12-02 12:59:21,873 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
2024-12-02 12:59:22,974 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 13:00:19,961 - web_analyzer - WARNING - Timeout waiting for selector .original-catalog-page
2024-12-02 13:00:25,125 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный: [Errno 22] Invalid argument: 'web_analyzer\\output\\20241202_125912_quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный.html'
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 255, in analyze_page
    html_path.write_text(html, encoding='utf-8')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
OSError: [Errno 22] Invalid argument: 'web_analyzer\\output\\20241202_125912_quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный.html'
2024-12-02 13:01:57,520 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 13:01:59,242 - web_analyzer - WARNING - Could not get response body: Response.text: Response body is unavailable for redirect responses
2024-12-02 13:02:01,152 - web_analyzer - WARNING - Could not get response body: Response.text: Response body is unavailable for redirect responses
2024-12-02 13:02:01,788 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:02:01,837 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 13:02:01,910 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:02:02,180 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:02:03,603 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x9a in position 1: invalid start byte
2024-12-02 13:02:05,411 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0xca in position 12: invalid continuation byte
2024-12-02 13:02:05,614 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
2024-12-02 13:02:06,651 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 13:03:02,931 - web_analyzer - WARNING - Timeout waiting for selector .original-catalog-page
2024-12-02 13:03:08,097 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный: [Errno 22] Invalid argument: 'web_analyzer\\output\\20241202_130157_quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный.html'
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 255, in analyze_page
    scripts_info = await self._extract_javascript(page, timestamp)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
OSError: [Errno 22] Invalid argument: 'web_analyzer\\output\\20241202_130157_quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный.html'
2024-12-02 13:03:11,800 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 13:03:13,376 - web_analyzer - WARNING - Could not get response body: Response.text: Response body is unavailable for redirect responses
2024-12-02 13:03:15,491 - web_analyzer - WARNING - Could not get response body: Response.text: Response body is unavailable for redirect responses
2024-12-02 13:03:16,135 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 13:03:16,187 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:03:16,319 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:03:16,634 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:03:19,637 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0xb8 in position 1: invalid start byte
2024-12-02 13:03:20,050 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
2024-12-02 13:03:20,994 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 13:04:17,274 - web_analyzer - WARNING - Timeout waiting for selector .original-catalog-page
2024-12-02 13:05:20,901 - web_analyzer - ERROR - Error closing context: : no running event loop
2024-12-02 13:05:20,903 - web_analyzer - ERROR - Error closing browser: Browser.close: no running event loop
2024-12-02 13:10:13,104 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 13:10:18,020 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 13:10:18,454 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:10:21,313 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0xb8 in position 1: invalid start byte
2024-12-02 13:10:21,736 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
2024-12-02 13:11:19,317 - web_analyzer - WARNING - Timeout waiting for selector .original-catalog-page
2024-12-02 13:11:29,331 - web_analyzer - WARNING - Reached 10 second timeout waiting for requests to complete
2024-12-02 13:11:29,450 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный: [Errno 22] Invalid argument: 'web_analyzer\\output\\20241202_131013_quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный.html'
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 270, in analyze_page
    path=str(screenshot_path),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
OSError: [Errno 22] Invalid argument: 'web_analyzer\\output\\20241202_131013_quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный.html'
2024-12-02 13:11:29,460 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:12:35,215 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 13:12:37,487 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:12:37,767 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 13:12:40,520 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0xd2 in position 10: invalid continuation byte
2024-12-02 13:12:40,944 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
2024-12-02 13:13:06,279 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%20%D0%BC%D0%B0%D1%81%D0%BB%D1%8F%D0%BD%D1%8B%D0%B9", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 238, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%20%D0%BC%D0%B0%D1%81%D0%BB%D1%8F%D0%BD%D1%8B%D0%B9", waiting until "networkidle"

2024-12-02 13:13:06,289 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:14:14,367 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 13:14:27,828 - web_analyzer - WARNING - Could not get response body: Response.body: Response body is unavailable for redirect responses
2024-12-02 13:14:31,309 - web_analyzer - WARNING - Could not get response body: Response.text: Protocol error (Network.getResponseBody): No data found for resource with given identifier
2024-12-02 13:14:31,566 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
2024-12-02 13:14:32,804 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0xed in position 1: invalid continuation byte
2024-12-02 13:14:32,894 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
2024-12-02 13:14:33,219 - web_analyzer - WARNING - Could not decode post_data: 'utf-8' codec can't decode byte 0xf1 in position 3: invalid continuation byte
2024-12-02 13:14:45,280 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%20%D0%BC%D0%B0%D1%81%D0%BB%D1%8F%D0%BD%D1%8B%D0%B9", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 238, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%20%D0%BC%D0%B0%D1%81%D0%BB%D1%8F%D0%BD%D1%8B%D0%B9", waiting until "networkidle"

2024-12-02 13:14:45,290 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:18:37,527 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный
2024-12-02 13:19:08,507 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=Фильтр%20масляный: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%20%D0%BC%D0%B0%D1%81%D0%BB%D1%8F%D0%BD%D1%8B%D0%B9", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/list-nodes/quick-nodes?catalogCode=HONDA2017&carId=10161&quickGroupId=2&carSsd=JCpLd0dacmJ5VF9aUEJsTW56bmVhX3lNSFY5Zkxzbkp1ZG00eWprTmplN2ZubDRlUGdwYktlOU5yZTJ1djk1UFd6cnFTWmtPN2xfZVB1MFlDOGhkWGR4TWpybTUyZXhNMEFBQUFBX3lyQmFnPT0k&wizzardSsd=JCpLd0VjUmpsWFVCMW9IUnBSSEdwRlMxSUFBQUFBSDJyZDlRPT0k&t=1733133259608&name=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%20%D0%BC%D0%B0%D1%81%D0%BB%D1%8F%D0%BD%D1%8B%D0%B9", waiting until "networkidle"

2024-12-02 13:19:08,517 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:34:05,126 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/honda/all
2024-12-02 13:34:36,152 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/honda/all: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/honda/all", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/honda/all", waiting until "networkidle"

2024-12-02 13:34:36,161 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:47:26,627 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/honda/all
2024-12-02 13:47:57,580 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/honda/all: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/honda/all", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/honda/all", waiting until "networkidle"

2024-12-02 13:47:57,590 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:48:57,556 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/honda/all
2024-12-02 13:49:28,547 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/honda/all: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/honda/all", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/honda/all", waiting until "networkidle"

2024-12-02 13:49:28,557 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:49:28,562 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/honda/all
2024-12-02 13:49:59,591 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/honda/all: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/honda/all", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/honda/all", waiting until "networkidle"

2024-12-02 13:49:59,602 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:49:59,607 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:49:59,607 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:50:01,618 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/toyota/all
2024-12-02 13:50:32,646 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/toyota/all: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/toyota/all", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/toyota/all", waiting until "networkidle"

2024-12-02 13:50:32,656 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:50:32,659 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/toyota/all
2024-12-02 13:50:32,665 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:51:03,686 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/toyota/all: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/toyota/all", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/toyota/all", waiting until "networkidle"

2024-12-02 13:51:03,697 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:51:03,702 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:51:03,702 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:51:03,703 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:51:03,703 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:51:03,703 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:51:03,703 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:51:05,717 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/nissan/all
2024-12-02 13:51:36,722 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/nissan/all: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/nissan/all", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/nissan/all", waiting until "networkidle"

2024-12-02 13:51:36,733 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:51:36,737 - web_analyzer - INFO - Starting analysis of https://www.autodoc.ru/catalogs/original/nissan/all
2024-12-02 13:51:36,743 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,700 - web_analyzer - ERROR - Error analyzing https://www.autodoc.ru/catalogs/original/nissan/all: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/nissan/all", waiting until "networkidle"
Traceback (most recent call last):
  File "C:\Users\alesha229\Desktop\Бот тг\web_analyzer\web_client.py", line 224, in analyze_page
    response = await page.goto(url, wait_until="networkidle")
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8973, in goto
    await self._impl_obj.goto(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\alesha229\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://www.autodoc.ru/catalogs/original/nissan/all", waiting until "networkidle"

2024-12-02 13:52:07,712 - web_analyzer - ERROR - Error closing context: BrowserContext.close: Target page, context or browser has been closed
2024-12-02 13:52:07,718 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,718 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,718 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,718 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,718 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,718 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,718 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,719 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
2024-12-02 13:52:07,720 - web_analyzer - ERROR - Error saving request data: Request.response: Target page, context or browser has been closed
